version: "3.7"
services:
  frontend:
    container_name: comacoweb
    build:
      context: .
      dockerfile: Dockerfile
    image: mavalderrama/comacow
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
#  backend:
#    container_name: awesome_server
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    image: vikasraj/awesome_server
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./server:/usr/src/app